#A simple makefile for MinGW-W64 ( or MinGW )
CXX=g++
LFLAGS=-L../lib -lusbx
CXXFLAGS=-I../lib -mwindows -s -O3
SRCS=testlib.c stress.c
OUTB=testlib

all: clean ${OUTB}

clean:
	@echo Cleaning $@ ...
	@rm -rf ${OUTB}

${OUTB}: ${SRCS}
	@echo Compile $@ ...
	@$(CXX) $(SRCS) $(LFLAGS) $(CXXFLAGS) -o ${OUTB}
